// Elektro-Leistungsverzeichnis (LV) neuverdrahtet 2026: umfassender Preis-
// katalog mit 240 Positionen über alle Gewerke-Schwerpunkte des Betriebs
// (Elektroinstallation, Wallbox, Photovoltaik, Beleuchtung, Smart Home, KNX,
// Mess-/Regeltechnik, Wärmepumpe, DGUV-Prüfung, E-Check, Wartung, Sicherheits-
// technik, Brandmeldeanlagen) - aus der Excel-Vorlage
// leistungsverzeichnis/Elektro-Leistungsverzeichnis-neuverdrahtet-2026.xlsx
// übernommen. Über den Button "Standard-Kataloge importieren" in Artikel &
// Leistungen aufrufbar - bereits vorhandene Bezeichnungen werden dabei
// übersprungen. Die Excel-Datei bleibt die editierbare Quelle (z.B. für
// Ausdrucke); bei Preisänderungen dort UND hier pflegen.

const STEUERSATZ = 19;
const GEWERK = 'elektro';

// typ: 'artikel' (Material), 'leistung' (Arbeitszeit/Lohn oder fertig
// kalkulierte Komplettposition), 'geraet' (Gerät/Technik-Endprodukt).
function pos(typ, bezeichnung, einheit, preis, unterkategorie) {
  return { typ, bezeichnung, beschreibung: '', einheit, einkaufspreis: 0, aufschlagProzent: 0, preis, steuersatz: STEUERSATZ, gewerk: GEWERK, unterkategorie };
}

export const STANDARD_KATALOG_ELEKTRO_LV = [
  // --- Elektroinstallation ---
  pos("artikel", "NYM-J 3x1,5 mm² Installationsleitung", "m", 2.1, "Elektroinstallation"),
  pos("artikel", "NYM-J 3x2,5 mm² Installationsleitung", "m", 2.8, "Elektroinstallation"),
  pos("artikel", "NYM-J 5x1,5 mm² Installationsleitung", "m", 3.6, "Elektroinstallation"),
  pos("artikel", "Installationsrohr flexibel (Leerrohr) M20", "m", 1.4, "Elektroinstallation"),
  pos("artikel", "Unterputzdose Standard", "Stk.", 1.8, "Elektroinstallation"),
  pos("artikel", "Abzweigdose Auf-/Unterputz", "Stk.", 3.2, "Elektroinstallation"),
  pos("artikel", "Schalter-/Steckdoseneinsatz Standard (Serie)", "Stk.", 9.5, "Elektroinstallation"),
  pos("artikel", "Schalter-/Steckdosenrahmen inkl. Abdeckung", "Stk.", 7.8, "Elektroinstallation"),
  pos("artikel", "FI-Schutzschalter (RCD) 2-polig 25A/30mA", "Stk.", 68, "Elektroinstallation"),
  pos("artikel", "FI/LS-Kombischalter 1-polig 16A, Typ A", "Stk.", 145, "Elektroinstallation"),
  pos("artikel", "Leitungsschutzschalter (LS) B16, 1-polig", "Stk.", 14.5, "Elektroinstallation"),
  pos("artikel", "Sicherungs-/Verteilerschrank UP, 3-reihig", "Stk.", 165, "Elektroinstallation"),
  pos("artikel", "Potentialausgleichsschiene inkl. Zubehör", "Stk.", 32, "Elektroinstallation"),
  pos("artikel", "Verbindungsklemmen (Steckklemmen) Set", "Stk.", 4.5, "Elektroinstallation"),
  pos("artikel", "Kabelkanal / Brüstungskanal", "m", 8.9, "Elektroinstallation"),
  pos("leistung", "Facharbeiterstunde Elektroinstallation", "Std.", 68, "Elektroinstallation"),
  pos("leistung", "Meisterstunde (Planung / Abnahme)", "Std.", 89, "Elektroinstallation"),
  pos("leistung", "Kabel verlegen Unterputz (Schlitz stemmen, verputzen)", "m", 12.5, "Elektroinstallation"),
  pos("leistung", "Kabel verlegen Aufputz / im Kabelkanal", "m", 5.8, "Elektroinstallation"),
  pos("leistung", "Unterputzdose setzen inkl. Kernbohrung", "Stk.", 18, "Elektroinstallation"),
  pos("leistung", "Schalter/Steckdose montieren u. anschließen", "Stk.", 14, "Elektroinstallation"),
  pos("leistung", "Sicherungskasten anschließen u. verdrahten (je Stromkreis)", "Stk.", 32, "Elektroinstallation"),
  pos("leistung", "Zählerschrank-Anschluss herstellen", "Psch.", 180, "Elektroinstallation"),
  pos("leistung", "Anschluss Herd / Backofen (Starkstrom)", "Stk.", 65, "Elektroinstallation"),
  pos("leistung", "Anschluss Durchlauferhitzer", "Stk.", 55, "Elektroinstallation"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Elektroinstallation"),
  pos("leistung", "Entsorgung Altmaterial", "Psch.", 45, "Elektroinstallation"),
  pos("geraet", "Rauchwarnmelder vernetzt (funkbasiert)", "Stk.", 42, "Elektroinstallation"),
  pos("geraet", "Klingel-/Gegensprechanlage Set", "Stk.", 165, "Elektroinstallation"),
  pos("geraet", "Zeitschaltuhr / Treppenlichtautomat", "Stk.", 38, "Elektroinstallation"),
  pos("geraet", "Überspannungsschutz Typ 2 (SPD)", "Stk.", 95, "Elektroinstallation"),
  pos("leistung", "Steckdose UP komplett (Material + Montage)", "Stk.", 42, "Elektroinstallation"),
  pos("leistung", "Lichtauslass Decke komplett (Material + Montage)", "Stk.", 48, "Elektroinstallation"),
  pos("leistung", "Schalterstelle komplett (Material + Montage)", "Stk.", 39, "Elektroinstallation"),
  pos("leistung", "Sicherungskasten-Neuinstallation komplett, bis 12 Stromkreise", "Psch.", 1450, "Elektroinstallation"),
  pos("leistung", "Kompletterneuerung Elektroinstallation Altbau", "m²", 95, "Elektroinstallation"),
  pos("leistung", "Neuinstallation Elektro Neubau (Rohinstallation)", "m²", 58, "Elektroinstallation"),
  pos("leistung", "FI/LS-Kombiautomat komplett eingebaut", "Stk.", 195, "Elektroinstallation"),
  pos("leistung", "Potentialausgleich komplett hergestellt", "Psch.", 220, "Elektroinstallation"),

  // --- Wallbox ---
  pos("artikel", "Wallbox 11 kW, geeicht", "Stk.", 890, "Wallbox"),
  pos("artikel", "Wallbox 22 kW mit Lastmanagement", "Stk.", 1490, "Wallbox"),
  pos("artikel", "NYY-J 5x6 mm² Erdkabel", "m", 6.8, "Wallbox"),
  pos("artikel", "NYY-J 5x10 mm² Erdkabel", "m", 9.6, "Wallbox"),
  pos("artikel", "FI-Schutzschalter Typ B, 25A/30mA", "Stk.", 385, "Wallbox"),
  pos("artikel", "LS-Schalter B16/B20/B32", "Stk.", 16, "Wallbox"),
  pos("artikel", "Leerrohr für Erdverlegung inkl. Kabelschutzrohr", "m", 4.2, "Wallbox"),
  pos("artikel", "Wallbox-Unterverteiler (Zählerschrank-Erweiterung)", "Stk.", 220, "Wallbox"),
  pos("artikel", "Energiezähler (MID-konform)", "Stk.", 145, "Wallbox"),
  pos("leistung", "Facharbeiterstunde Wallbox-Montage", "Std.", 68, "Wallbox"),
  pos("leistung", "Montage Wallbox an Wand / Stele", "Stk.", 120, "Wallbox"),
  pos("leistung", "Kabelverlegung Innen (UP/AP)", "m", 12.5, "Wallbox"),
  pos("leistung", "Kabelverlegung Erdreich inkl. Grabenaushub (Hand)", "m", 28, "Wallbox"),
  pos("leistung", "Kernbohrung Wanddurchbruch", "Stk.", 65, "Wallbox"),
  pos("leistung", "Anmeldung / Genehmigung beim Netzbetreiber", "Psch.", 85, "Wallbox"),
  pos("leistung", "Inbetriebnahme u. Messprotokoll (VDE 0100-600)", "Psch.", 95, "Wallbox"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Wallbox"),
  pos("leistung", "Wallbox-Komplettpaket 11 kW, bis 15 m Kabelweg", "Psch.", 1690, "Wallbox"),
  pos("leistung", "Wallbox-Komplettpaket 22 kW mit Lastmanagement", "Psch.", 2390, "Wallbox"),
  pos("leistung", "Zusatzkabelweg über 15 m, Erdverlegung (je weitere m)", "m", 38, "Wallbox"),
  pos("leistung", "Zweite Wallbox mit Lastmanagement-Anbindung komplett", "Psch.", 990, "Wallbox"),

  // --- Photovoltaik (Elektroanschluss) ---
  pos("artikel", "AC-Zählerschrank-Kombination (PV-fähig)", "Stk.", 450, "Photovoltaik (Elektroanschluss)"),
  pos("artikel", "AC-Kabel NYM-J 5x6 mm² Wechselrichteranschluss", "m", 6.5, "Photovoltaik (Elektroanschluss)"),
  pos("artikel", "FI-Schutzschalter Typ B (Wechselrichter)", "Stk.", 385, "Photovoltaik (Elektroanschluss)"),
  pos("artikel", "Überspannungsschutz Typ 1+2 (AC-Seite)", "Stk.", 165, "Photovoltaik (Elektroanschluss)"),
  pos("artikel", "Zweirichtungszähler-Vorbereitung", "Stk.", 95, "Photovoltaik (Elektroanschluss)"),
  pos("artikel", "Backup-/Notstromsteckdose Set", "Stk.", 245, "Photovoltaik (Elektroanschluss)"),
  pos("artikel", "Smart-Meter-Gateway Anschlussmaterial", "Stk.", 85, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Facharbeiterstunde PV-Elektroanschluss", "Std.", 68, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Zählerschrank-Umbau für PV-Einspeisung", "Psch.", 380, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "AC-Anschluss Wechselrichter herstellen", "Stk.", 145, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Anmeldung Netzbetreiber (Einspeisezusage)", "Psch.", 95, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Anmeldung Marktstammdatenregister", "Psch.", 45, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Inbetriebnahme u. Messprotokoll", "Psch.", 120, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "PV-Elektroanschluss Komplettpaket bis 10 kWp", "Psch.", 1450, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "PV-Elektroanschluss Komplettpaket 10–30 kWp", "Psch.", 2190, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Speicher-Nachrüstung elektroseitig komplett", "Psch.", 890, "Photovoltaik (Elektroanschluss)"),
  pos("leistung", "Notstrom-/Ersatzstromanschluss komplett", "Psch.", 690, "Photovoltaik (Elektroanschluss)"),

  // --- Beleuchtung ---
  pos("artikel", "LED-Panel 62x62 cm, 40 W", "Stk.", 68, "Beleuchtung"),
  pos("artikel", "LED-Einbaustrahler-Set (dimmbar)", "Stk.", 24, "Beleuchtung"),
  pos("artikel", "Bewegungsmelder UP/AP", "Stk.", 32, "Beleuchtung"),
  pos("artikel", "Dimmer-Einsatz (Phasenan-/-abschnitt)", "Stk.", 45, "Beleuchtung"),
  pos("artikel", "Trafo / Netzteil LED 12V/24V", "Stk.", 38, "Beleuchtung"),
  pos("artikel", "Lichtschiene 3-Phasen inkl. Zubehör", "m", 42, "Beleuchtung"),
  pos("artikel", "Pendelleuchten-Anschlussdose", "Stk.", 12, "Beleuchtung"),
  pos("leistung", "Facharbeiterstunde Beleuchtungstechnik", "Std.", 68, "Beleuchtung"),
  pos("leistung", "Lichtplanung / Beratung vor Ort", "Psch.", 95, "Beleuchtung"),
  pos("leistung", "Leuchtenmontage (Decke / Wand)", "Stk.", 28, "Beleuchtung"),
  pos("leistung", "Einbaustrahler-Montage inkl. Ausschnitt", "Stk.", 22, "Beleuchtung"),
  pos("leistung", "DALI-/Bussteuerleitung verlegen", "m", 8.5, "Beleuchtung"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Beleuchtung"),
  pos("leistung", "Einbaustrahler-Set komplett (5 Stk. inkl. Montage)", "Psch.", 245, "Beleuchtung"),
  pos("leistung", "Zimmerbeleuchtung Komplettpaket (Decke + Schalter)", "Psch.", 185, "Beleuchtung"),
  pos("leistung", "Außenbeleuchtung Komplettpaket inkl. Bewegungsmelder", "Psch.", 320, "Beleuchtung"),
  pos("leistung", "LED-Umrüstung pro Leuchtstelle komplett", "Stk.", 55, "Beleuchtung"),

  // --- Smart Home (Allgemein) ---
  pos("artikel", "KNX-Universal-Aktor 4-fach", "Stk.", 145, "Smart Home (Allgemein)"),
  pos("artikel", "KNX-Taster 2-fach mit Display", "Stk.", 165, "Smart Home (Allgemein)"),
  pos("artikel", "Smart-Home-Gateway / Server", "Stk.", 320, "Smart Home (Allgemein)"),
  pos("artikel", "Funk-Aktor Steckdose / Schaltaktor", "Stk.", 55, "Smart Home (Allgemein)"),
  pos("artikel", "Rollladen-/Jalousieaktor", "Stk.", 68, "Smart Home (Allgemein)"),
  pos("artikel", "Heizungsaktor (Fußbodenheizung/Thermostat)", "Stk.", 58, "Smart Home (Allgemein)"),
  pos("artikel", "Präsenzmelder KNX", "Stk.", 95, "Smart Home (Allgemein)"),
  pos("leistung", "Facharbeiterstunde Smart-Home-Installation", "Std.", 68, "Smart Home (Allgemein)"),
  pos("leistung", "Systemplanung / Beratung", "Psch.", 120, "Smart Home (Allgemein)"),
  pos("leistung", "KNX-Programmierung je Raum", "Stk.", 85, "Smart Home (Allgemein)"),
  pos("leistung", "Inbetriebnahme Gesamtsystem", "Psch.", 220, "Smart Home (Allgemein)"),
  pos("leistung", "Einweisung Kunde (App / Bedienung)", "Psch.", 65, "Smart Home (Allgemein)"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Smart Home (Allgemein)"),
  pos("leistung", "Smart-Home Starter-Paket (3 Räume, Licht + Rollladen)", "Psch.", 1690, "Smart Home (Allgemein)"),
  pos("leistung", "Raumsteuerung komplett (Licht/Heizung/Rollladen je Raum)", "Stk.", 385, "Smart Home (Allgemein)"),
  pos("leistung", "Rollladensteuerung komplett (Material+Montage+Programmierung)", "Stk.", 165, "Smart Home (Allgemein)"),
  pos("leistung", "Sprachsteuerung-Integration (Alexa/Google) komplett", "Psch.", 145, "Smart Home (Allgemein)"),

  // --- KNX-Gebäudesystemtechnik ---
  pos("artikel", "KNX-Spannungsversorgung 640 mA inkl. Drossel", "Stk.", 145, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Busankoppler (Universal)", "Stk.", 35, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Universal-Binärausgang 8-fach", "Stk.", 185, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Jalousie-/Rollladenaktor 4-fach", "Stk.", 165, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Dimmaktor 4-fach", "Stk.", 195, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Tastsensor 4-fach mit Raumtemperaturregler", "Stk.", 185, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Wetterstation (Wind/Regen/Helligkeit)", "Stk.", 320, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-IP-Router / Schnittstelle", "Stk.", 245, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Busleitung JY(St)Y 2x2x0,8", "m", 1.6, "KNX-Gebäudesystemtechnik"),
  pos("artikel", "KNX-Visualisierungsserver (z. B. Gira/ABB/Loxone)", "Stk.", 590, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "Facharbeiterstunde KNX-Installation", "Std.", 68, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "Meisterstunde KNX-Planung / ETS-Programmierung", "Std.", 89, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "KNX-Busleitung verlegen", "m", 5.5, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "Montage / Anschluss KNX-Gerät (Aktor/Sensor)", "Stk.", 32, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "ETS-Projektierung je Gruppenadresse/Datenpunkt", "Stk.", 12, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "Inbetriebnahme u. Funktionstest Gesamtanlage", "Psch.", 280, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "Einweisung / Schulung Kunde am System", "Psch.", 95, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "KNX-Raumcontroller komplett (Taster + Aktor + Programmierung je Raum)", "Stk.", 420, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "KNX-Jalousiesteuerung komplett je Fenster", "Stk.", 185, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "KNX-Grundausstattung Einfamilienhaus (bis 8 Räume) komplett", "Psch.", 6900, "KNX-Gebäudesystemtechnik"),
  pos("leistung", "KNX-Visualisierung Komplettpaket (Server + Einrichtung + Einweisung)", "Psch.", 1290, "KNX-Gebäudesystemtechnik"),

  // --- Mess- und Regeltechnik (MSR) ---
  pos("artikel", "Temperaturfühler (PT100 / PT1000)", "Stk.", 28, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Feuchtefühler / Hygrostat", "Stk.", 45, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Drucktransmitter", "Stk.", 85, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Stromwandler für Energiemonitoring", "Stk.", 38, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Zeit-/Wochenschaltuhr digital", "Stk.", 42, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Raumtemperaturregler digital", "Stk.", 65, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "SPS-Kleinsteuerung / Logikmodul", "Stk.", 185, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Datenlogger / Energiemonitoring-Gateway", "Stk.", 145, "Mess- und Regeltechnik (MSR)"),
  pos("artikel", "Signalkabel (LiYCY, geschirmt)", "m", 2.4, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Facharbeiterstunde Mess- und Regeltechnik", "Std.", 68, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Meisterstunde MSR-Planung / Inbetriebnahme", "Std.", 89, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Montage / Anschluss Fühler oder Sensor", "Stk.", 28, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Verkabelung Signal-/Bussystem", "m", 6.5, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Programmierung Regler / SPS", "Psch.", 165, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Kalibrierung / Abgleich Messkette", "Psch.", 95, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Inbetriebnahme u. Funktionsprüfung", "Psch.", 120, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Energiemonitoring-Paket komplett (Zähler + Sensorik + Auswertung)", "Psch.", 890, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "Raumtemperatur-Regelung komplett (Fühler + Regler + Programmierung)", "Stk.", 245, "Mess- und Regeltechnik (MSR)"),
  pos("leistung", "SPS-Kleinsteuerung Komplettpaket (Material + Programmierung + Inbetriebnahme)", "Psch.", 1290, "Mess- und Regeltechnik (MSR)"),

  // --- Wärmepumpe (Elektroanschluss) ---
  pos("artikel", "Zählerschrank-Erweiterung für Wärmepumpe", "Stk.", 220, "Wärmepumpe (Elektroanschluss)"),
  pos("artikel", "Rundsteuerempfänger-Vorbereitung / Klemmen", "Stk.", 45, "Wärmepumpe (Elektroanschluss)"),
  pos("artikel", "Lastabwurfrelais (§14a EnWG)", "Stk.", 165, "Wärmepumpe (Elektroanschluss)"),
  pos("artikel", "NYY-J 5x6 mm² Zuleitung Außeneinheit", "m", 6.8, "Wärmepumpe (Elektroanschluss)"),
  pos("artikel", "Steuerleitung (LiYCY) Innen-/Außeneinheit", "m", 3.2, "Wärmepumpe (Elektroanschluss)"),
  pos("artikel", "LS-Schalter / FI für WP-Stromkreis", "Stk.", 85, "Wärmepumpe (Elektroanschluss)"),
  pos("artikel", "Potentialausgleich-Zubehör Außeneinheit", "Stk.", 28, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Facharbeiterstunde Wärmepumpen-Elektroanschluss", "Std.", 68, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Elektroanschluss Außeneinheit herstellen", "Psch.", 220, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Elektroanschluss Innen-/Speichereinheit", "Psch.", 165, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Kabelverlegung Innen / Außen", "m", 12.5, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Anmeldung Netzbetreiber (§14a steuerbare Verbrauchseinrichtung)", "Psch.", 95, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Inbetriebnahme u. Funktionsprüfung", "Psch.", 120, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Wärmepumpen-Elektroanschluss Komplettpaket", "Psch.", 1290, "Wärmepumpe (Elektroanschluss)"),
  pos("leistung", "Zählerschrank-Erweiterung komplett für WP + PV kombiniert", "Psch.", 590, "Wärmepumpe (Elektroanschluss)"),

  // --- DGUV-Prüfung (DGUV Vorschrift 3) ---
  pos("artikel", "Prüfplakette (Anlage / Betriebsmittel)", "Stk.", 1.2, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("artikel", "Prüfetikett mit Barcode / QR", "Stk.", 1.8, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Facharbeiterstunde Prüftechnik", "Std.", 68, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Prüfung ortsfeste elektrische Anlage (Grundpreis)", "Psch.", 145, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Prüfung ortsveränderliches Betriebsmittel (je Gerät)", "Stk.", 4.5, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Prüfung Maschine / Anlage (je Maschine)", "Stk.", 35, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Prüfung Schaltschrank / Verteilung", "Stk.", 65, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Dokumentation u. Prüfbericht", "Psch.", 45, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Mängelbeseitigung (Kleinreparatur, je angef. Stunde)", "Std.", 68, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "DGUV-V3-Prüfpaket Kleinbetrieb (bis 50 Geräte)", "Psch.", 390, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "DGUV-V3-Prüfpaket Mittelbetrieb (bis 150 Geräte)", "Psch.", 890, "DGUV-Prüfung (DGUV Vorschrift 3)"),
  pos("leistung", "Wiederholungsprüfung ortsfeste Anlage komplett", "Psch.", 245, "DGUV-Prüfung (DGUV Vorschrift 3)"),

  // --- E-Check ---
  pos("artikel", "Prüfplakette E-Check", "Stk.", 1.2, "E-Check"),
  pos("leistung", "Facharbeiterstunde E-Check", "Std.", 68, "E-Check"),
  pos("leistung", "E-Check Wohnung (bis 80 m²)", "Psch.", 165, "E-Check"),
  pos("leistung", "E-Check Einfamilienhaus", "Psch.", 245, "E-Check"),
  pos("leistung", "E-Check Gewerbe (Grundpreis, je nach Größe)", "Psch.", 320, "E-Check"),
  pos("leistung", "Thermografie-Zusatzprüfung", "Psch.", 145, "E-Check"),
  pos("leistung", "Prüfprotokoll u. Dokumentation", "Psch.", 35, "E-Check"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "E-Check"),
  pos("leistung", "E-Check Komplettpaket Wohnung inkl. Protokoll u. Plakette", "Psch.", 195, "E-Check"),
  pos("leistung", "E-Check Komplettpaket Haus inkl. Thermografie", "Psch.", 365, "E-Check"),

  // --- Wartung ---
  pos("leistung", "Facharbeiterstunde Wartung / Service", "Std.", 68, "Wartung"),
  pos("leistung", "Wartung Elektroinstallation (jährlich, Grundpreis)", "Psch.", 145, "Wartung"),
  pos("leistung", "Wartung PV-Anlage (elektroseitig, jährlich)", "Psch.", 185, "Wartung"),
  pos("leistung", "Wartung Wallbox (jährlich)", "Psch.", 95, "Wartung"),
  pos("leistung", "Wartung Wärmepumpe (elektroseitig, jährlich)", "Psch.", 95, "Wartung"),
  pos("leistung", "Wartung Smart-Home-System (jährlich)", "Psch.", 145, "Wartung"),
  pos("leistung", "Wartung Beleuchtungsanlage (jährlich)", "Psch.", 85, "Wartung"),
  pos("leistung", "Störungsbehebung (Grundpreis + Zeit)", "Psch.", 65, "Wartung"),
  pos("leistung", "Thermografie-Untersuchung Verteilung", "Psch.", 165, "Wartung"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Wartung"),
  pos("leistung", "Wartungsvertrag Basic (1x jährlich, 1 Gewerk)", "Psch./Jahr", 185, "Wartung"),
  pos("leistung", "Wartungsvertrag Komfort (1x jährlich, bis 3 Gewerke)", "Psch./Jahr", 420, "Wartung"),
  pos("leistung", "Wartungsvertrag Premium (2x jährlich, alle Gewerke inkl. Thermografie)", "Psch./Jahr", 890, "Wartung"),

  // --- Sicherheitstechnik ---
  pos("artikel", "Alarmzentrale (Funk/Draht, modular)", "Stk.", 320, "Sicherheitstechnik"),
  pos("artikel", "Bewegungsmelder Alarm (Innen)", "Stk.", 55, "Sicherheitstechnik"),
  pos("artikel", "Tür-/Fensterkontakt (Funk)", "Stk.", 32, "Sicherheitstechnik"),
  pos("artikel", "Sirene Innen / Außen", "Stk.", 85, "Sicherheitstechnik"),
  pos("artikel", "Überwachungskamera (IP, PoE)", "Stk.", 145, "Sicherheitstechnik"),
  pos("artikel", "Bedienteil / Tastatur", "Stk.", 95, "Sicherheitstechnik"),
  pos("artikel", "Notstromversorgung (Akku-Backup)", "Stk.", 65, "Sicherheitstechnik"),
  pos("leistung", "Facharbeiterstunde Sicherheitstechnik", "Std.", 68, "Sicherheitstechnik"),
  pos("leistung", "Montage Alarmzentrale", "Stk.", 120, "Sicherheitstechnik"),
  pos("leistung", "Montage / Anschluss Melder/Kontakt je Stück", "Stk.", 25, "Sicherheitstechnik"),
  pos("leistung", "Programmierung / Inbetriebnahme Gesamtsystem", "Psch.", 165, "Sicherheitstechnik"),
  pos("leistung", "Einweisung Kunde", "Psch.", 45, "Sicherheitstechnik"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Sicherheitstechnik"),
  pos("leistung", "Alarmanlagen-Komplettpaket Wohnung (bis 4 Melder)", "Psch.", 990, "Sicherheitstechnik"),
  pos("leistung", "Alarmanlagen-Komplettpaket Haus (bis 8 Melder + 2 Kameras)", "Psch.", 1890, "Sicherheitstechnik"),
  pos("leistung", "Kamera-Nachrüstung komplett (je Kamera)", "Stk.", 220, "Sicherheitstechnik"),

  // --- Brandmeldeanlagen ---
  pos("artikel", "Rauchwarnmelder vernetzt (Funk, VdS)", "Stk.", 45, "Brandmeldeanlagen"),
  pos("artikel", "Wärmemelder (VdS-anerkannt)", "Stk.", 58, "Brandmeldeanlagen"),
  pos("artikel", "Brandmeldezentrale (Kleinanlage, modular)", "Stk.", 890, "Brandmeldeanlagen"),
  pos("artikel", "Handfeuermelder (Druckknopfmelder)", "Stk.", 65, "Brandmeldeanlagen"),
  pos("artikel", "Alarmsirene / Blitzleuchte", "Stk.", 95, "Brandmeldeanlagen"),
  pos("artikel", "Funktionserhaltkabel (E30/E90)", "m", 8.5, "Brandmeldeanlagen"),
  pos("artikel", "Feuerwehr-Bedienfeld (FBF)", "Stk.", 320, "Brandmeldeanlagen"),
  pos("leistung", "Facharbeiterstunde Brandmeldetechnik", "Std.", 68, "Brandmeldeanlagen"),
  pos("leistung", "Montage Brandmeldezentrale", "Psch.", 320, "Brandmeldeanlagen"),
  pos("leistung", "Montage Melder je Stück", "Stk.", 28, "Brandmeldeanlagen"),
  pos("leistung", "Verkabelung Funktionserhalt (je m)", "m", 6.5, "Brandmeldeanlagen"),
  pos("leistung", "Programmierung / Inbetriebnahme BMA", "Psch.", 280, "Brandmeldeanlagen"),
  pos("leistung", "Abnahme durch Sachverständigen (Koordination)", "Psch.", 220, "Brandmeldeanlagen"),
  pos("leistung", "Wartung BMA (jährlich, DIN 14675)", "Psch.", 245, "Brandmeldeanlagen"),
  pos("leistung", "Anfahrtspauschale", "Psch.", 39, "Brandmeldeanlagen"),
  pos("leistung", "Rauchwarnmelder-Paket Wohnung (bis 6 Melder, vernetzt, komplett)", "Psch.", 490, "Brandmeldeanlagen"),
  pos("leistung", "Brandmeldeanlage-Komplettpaket Gewerbe klein (bis 15 Melder)", "Psch.", 3890, "Brandmeldeanlagen"),
  pos("leistung", "Wartungspaket BMA jährlich komplett", "Psch./Jahr", 320, "Brandmeldeanlagen"),

];
